Simulation = "DebianUpdateOneClient"
Servers = 4
Bf = 2
Rounds = 10
CloseWait = 6000
Height = 10
Base = 4
RunWait = 3600
Hosts = 4
Delay = 50

Packages, PackagesLatestHash, Snapshots, Releases
"clamav tzdata", "c322ccd4f4d09e57adfdff2f4e582c4aa6618f89d0d33207d4dc8e46e6b903d2 64f42bcd3b116ce57329140eec90bbfbdcc1f135a85b4efe476790fd925ddc2c", "stable-update"
